### ISSUE TITLE
腾讯视频外链

### ISSUE THREAD

**Issue by ivysrono** [levinit/bye-flash-hello-html5#10]
- https://www.yikeweiqi.com/video/video2/xuying/15076/

这个页面的视频只发现在微信内置浏览器中可以免flash直接播放，但简单的伪装成微信内置浏览器的 ua 无效。

- https://view.inews.qq.com/a/TEC2016121302749602

这个是可以通过简单伪装 ua 实现的。

**Comment by levinit** [comment]
外链当然时不行的了 因为油猴脚本是根据不同域名/地址进行工作的呀 你可以把yikeweiqi这个网站添加到脚本前面
```javascript
// @include     *://*yikeweiqi.com/video/*
```
这个网站的https证书是有问题的，firefox/chrome不认可（最近几大浏览器对https更严格了），你将ua改成Android/IOS，再把网址的https改成http试试看就能播放了。
第二个同理

**Comment by ivysrono** [comment]
第二个毕竟也是腾讯的网站，所以我觉得可以加入到你的脚本的原生支持当中。

至于第一个的问题是：
- 在移动端，https页面下的外链视频只有微信浏览器能播放 ；http页面下的外链视频可以在移动版Chrome正常播放，移动版Firefox的播放方式有点奇怪，但还是可以的。
-在桌面端，无论我是用chrome还是Firefox，无论是http还是https，无论伪装成上述三种ua中的哪一种，坚持提示使用flash。
脚本如下：
```
// ==UserScript==
// @name New Script
// @namespace Violentmonkey Scripts
// @include          *://view.inews.qq.com/*
// @include          *://*yikeweiqi.com/video/*
// @grant none
// @version          0.1
// @run-at           document-start
// ==/UserScript==
Object.defineProperty(navigator, 'plugins', {
  get: function () {
    return { length: 0 };
  }
});
'use strict';
Object.defineProperty(navigator,"userAgent",{value:"Mozilla/5.0 (Linux; Android 8.0.0; Build/OPR6.170623.013) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36",writable:false,configurable:false,enumerable:true});
```

**Comment by levinit** [comment]
油猴脚本只针对include规则匹配的网站生效 外链不能的吧
不同版本的移动ua 有的能播放 有的不能播放 我试了几个都不行诶
这个网站毕竟是小众网站
建议方案：
1. 使用user-agent-switcher 切成android/ios即可播放（需要url的协议为http 火狐下f12查看得知该网站[混合了http和https](https://developer.mozilla.org/zh-CN/docs/Security/MixedContent?utm_campaign=default&utm_medium=firefox-console-errors&utm_source=mozilla)被火狐拦截了 估计chrome也是如此 ）
可以写个脚本自动跳转https到http
```javascript
// ==UserScript==
// @name        跳转https到http
// @include     *://*yikeweiqi.com/video/*
// @run-at      document-start
// @version     0.1
// @grant       none
// ==/UserScript==
//'use strict';

if (location.protocol === 'https:' && location.host === 'www.yikeweiqi.com') {
  var url = location.href;
  url = url.replace('https', 'http');
  location.replace(url);
}
```
2. 该网站视频多使用腾讯视频连接 建议直接在腾讯视频上收看
3. 围棋网站、视频等资源这么多诶 围棋tv 101围棋网这些 😰像这种中盘的 一搜一堆 软件如围棋宝典也是不错哒

**Comment by ivysrono** [comment]
我倒不是想看这视频，只是想搞明白这种外链怎么解决罢了。
也是棋迷啊，资源这么清楚～

**Comment by levinit** [comment]
试了用ua切换工具可以放 不过要改成http 该网站https 会提示混合资源 然后被浏览器给封锁掉 把那个ua写在脚本里 没反应 可能也和这个有关吧
以前常下棋玩 也就会下的水平 1d都没有 好久没碰了 都不知道什么水平了



在 ivysrono <notifications@github.com>，2018年2月22日 下午11:15寫到：

我倒不是想看这视频，只是想搞明白这种外链怎么解决罢了。
也是棋迷啊，资源这么清楚～

**Comment by ivysrono** [comment]
这好像是第一个HeaderEditor扩展伪装ua搞不定的网站，我还以为能通过脚本跟强力解决。
谢谢，学到很多。

**Comment by ivysrono** [comment]
搞定了：[Scripts/HTML5-video-player.user.js at master · ivysrono/Scripts](https://github.com/ivysrono/Scripts/blob/master/HTML5-video-player.user.js)

原来是iframe的原因，GM脚本会将iframe是为独立的网页，所以需要就iframe的src进行适配。
