### ISSUE TITLE
希望支持腾讯课堂

### ISSUE THREAD

**Issue by LostInsight** [levinit/bye-flash-hello-html5#13]
RT，腾讯课堂移动端支持h5，但是pc端不支持
https://ke.qq.com/

**Comment by levinit** [comment]
腾讯课堂pc端可以不用flash吧 我也偶尔用呢 我们用的是一个腾讯课堂么

**Comment by LostInsight** [comment]
@levinit 我这里打开只有flash，系统64位windows 10，浏览器chrome 67
把ke.qq.com和7.url.cn的flash都禁用后依然是flash
试过无插件模式启动，依然是flash
改ua无效，chrome开发者模式模拟移动端无法显示视频
firefox模拟chrome也无法播放

**Comment by levinit** [comment]
@LostInsight  同67 可以用 ……
