### ISSUE TITLE
可以考虑加个百度网盘么

### ISSUE THREAD

**Issue by lychichem** [levinit/bye-flash-hello-html5#2]
虽然chrome高版本默认喂html5了，可是火狐和edge用户表示哭哭，大佬可以考虑添加一下么，代码的话，除了切UA到mac以外加这一段就好（我从gf上的百度网盘h5这个脚本里copy过来的）：
`Object.defineProperty(navigator, 'plugins', {get: function() {return {length: 0};}});`只是目前似乎反应速度有点捉急，另外时常出现先提示下载flash那个按钮，再刷新一遍才给html5的情况，不知道咋修。
另外优酷部分的修复可以考虑借鉴一下https://greasyfork.org/scripts/30432-ykh5p 如何开启html5的部分

**Comment by levinit** [comment]
我平时很少用百度，不过刚刚试着传了几个视频 都能很顺畅地播放（我没flash) 浏览器是firefox55.03 
优酷那天下午突然撤了html5 我用着用着就发现了 ykh5p我也装过两次 都没有起作用
[这里](https://github.com/esterTion/Youku-HTML5-Player)的插件 我试了下 也没起作用（可能我打开的方式不对）你可以试试看

**Comment by lychichem** [comment]
不是说播放流畅性，播放本身是流畅的，只是脚本的执行速度，似乎我这edge上如果是新开的百度视频播放页面脚本会稍微延迟一点运行？总之这个问题和第二个问题是相关的。
ykh5p脚本31号更新了，更新之后我这里是能用的（至少放秦时明月啥的是没问题）
浏览器是"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063"，脚本管理器用tampermonkey

**Comment by levinit** [comment]
edge的话有可能 windows不是自带flash嘛 找找edge的选项看看有没有关闭的 脚本已经是一开始就执行了 如果还是快不过flash也没办法（吧？） 只能劝你这种情况不用edge了
那个脚本我试了 我这用了不起效 奇怪了……我再看看吧  优酷改了规则很烦人……

**Comment by lychichem** [comment]
因为b站直播的关系我还没法关edge的flash……（b站直播html5播放器edge不支持）……不过也还好吧也就每次新开百度网盘页面的时候要刷新一下，之后就没事了

**Comment by levinit** [comment]
@lychichem 优酷又可以用了

**Comment by lychichem** [comment]
@levinit 嗯，我fork了一个自用版233，加了条b站直播的给edge用（他b的直播html5播放器还没开放给edge）
