### ISSUE TITLE
不支持网易云课堂付费观看的章节？

### ISSUE THREAD

**Issue by ivysrono** [levinit/bye-flash-hello-html5#3]
Firefox 55
TM
付费后播放器和视频都不载入，一片空白。
现在只能开其他浏览器用flash。

**Comment by levinit** [comment]
把你付费的课程的播放页面网址贴一下

**Comment by ivysrono** [comment]
付费前后的播放器页面是不一样的，给你也没用，或者说随便买一个才能看出来

**Comment by levinit** [comment]
有的付费的有试看章节吧我记得？

**Comment by ivysrono** [comment]
试看章节没问题，和免费章节是一样的可以html5
我的问题是必须付费才能看的部分，付了费还是只能开flash。
